
// CODE GENERATED BY AI TO SUPPORT THE INTERFACE

public class Money {
    // Constante para no crear objetos con valor 0 todo el rato
    public static final Money ZERO = new Money(0);

    private final int centimos; // Protegido y final (no puede cambiar)

    public Money(int centimos) {
        this.centimos = centimos;
    }

    // EL MÉTODO CLAVE
    public Money add(Money otro) {
        // NO cambiamos nuestro propio valor.
        // Devolvemos un OBJETO NUEVO con la suma.
        return new Money(this.centimos + otro.centimos);
    }
}